### ISSUE TITLE
Functions in the global space without component name prefix

### ISSUE THREAD

**Issue by mudrd8mz** [motivational-techniques/moodle-block_mt#2]
The block defines various functions in the global space such as `block_is_installed()` or `send_to_dashboard_if_no_block_installed()`. That goes against the naming guidelines and represents a potential risk for conflicts with future core functions.

Functions like this are generally better implemented as static method of a class which itself is correctly namespaced.

Ref: https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions

**Comment by menipe** [comment]
Updated naming of functions
